In [67]:
import pandas as pd

In [ ]:
#Import du df -> adresse du csv à vérifier à récupérer sur votre ordinateur
adresse=r"C:\Users\XXXXXX\data\données_traitées\Bibliographie_de_la_France_Tables_Littérature_Version détaillée_1824_v3.csv" #csv annoté (1824_v3) avec prédictions
df=pd.read_csv(adresse, encoding="utf-8",sep=";",header=0,dtype=str)
df = df.fillna("")
df['Identifiant ouvrage']=df['Identifiant ouvrage'].str.replace("http://ark.bnf.fr/ark:/","https://catalogue.bnf.fr/ark:/")
df["Identifiant auteur"]=df["Identifiant auteur"].str.replace("http://ark.bnf.fr/ark:/","https://catalogue.bnf.fr/ark:/")
df["Identifiant para-auteur"]=df["Identifiant para-auteur"].str.replace("http://ark.bnf.fr/ark:/","https://catalogue.bnf.fr/ark:/")

In [69]:
def verification_ouvrage(row):
    verite=row['Identifiant ouvrage'].split(";")
    prediction=row['Ouvrage_prédit'].split(" , ")
    resultat="Hors BNF"
    for vrai_ouvrage in verite:
        if not vrai_ouvrage.startswith("https://catalogue.bnf.fr/ark:/"):#Il ne s'agit pas d'un lien BNF, l'algorithme n'est normalement pas en capacité de le trouver
            continue 
        elif vrai_ouvrage in prediction:
            resultat="Prediction correcte"
            break #Dans le cas de multiples ouvrages, on se contentera d'un seul correctement prédit
        elif prediction==[""]:
            resultat="Non trouvé"
        else:
            resultat="Pas le même ouvrage"
    return resultat
df['predict_ouvrage_verif']=df.apply(verification_ouvrage,axis=1)
print(df['predict_ouvrage_verif'].value_counts())

predict_ouvrage_verif
Prediction correcte    1304
Non trouvé              384
Hors BNF                232
Pas le même ouvrage     187
Name: count, dtype: int64

In [57]:
#Visualisation direct des résultats d'un type (ouvrage)
verif_ouvrage="Non trouvé" #En choisir un parmi "Prediction correcte", "Non trouvé", "Hors BNF", "Pas le même ouvrage"
df[df['predict_ouvrage_verif']==verif_ouvrage][["Titre","Auteur","Identifiant ouvrage","Ouvrage_prédit","Auteur_prédit",'predict_ouvrage_verif']]

,Titre,Auteur,Identifiant ouvrage,Ouvrage_prédit,Auteur_prédit,predict_ouvrage_verif
11,Réflexions rapides sur une rébellion de débite...,l'Hermite du quartier Notre-Dame,https://catalogue.bnf.fr/ark:/12148/cb36388010m,,,Non trouvé
16,L’Entrée de Ferdinand VII à Madrid ; stances p...,"J. Brisset, garde du corps du roi de France",https://catalogue.bnf.fr/ark:/12148/cb301627424,,,Non trouvé
21,"Le Tambour de Logrono, ou Jeunesse et Valeur, ...",Adolphe C***;Combault,https://catalogue.bnf.fr/ark:/12148/cb30520618c,,,Non trouvé
22,"L’Arc de triomphe, tableau-vaudeville […], rep...",M. Carmouche;M. Emile Vander Burch,https://catalogue.bnf.fr/ark:/12148/cb301974366,,,Non trouvé
24,"Mon hommage à S. A. R. Mgr le duc d’Angoulême,...",Capelle,https://catalogue.bnf.fr/ark:/12148/cb30193716f,,,Non trouvé
...,...,...,...,...,...,...
2085,Petit Télémaque ou précis des avantures de Tél...,un instituteur,https://catalogue.bnf.fr/ark:/12148/cb33533867g,,,Non trouvé
2095,Fables nouvelles. Tome II,Auguste Rigaud,https://catalogue.bnf.fr/ark:/12148/cb31217142z,,,Non trouvé
2100,Pamphlet des pamphlets. Deuxième édition,"Paul Louis Courier, vigneron",https://catalogue.bnf.fr/ark:/12148/cb36315982s,,,Non trouvé
2102,"La Pauvre enfant, chant élégiaque",,https://catalogue.bnf.fr/ark:/12148/cb335286370,,,Non trouvé
2106,"Phædri, liberti Augusti, fabularum libri quinq...","Phèdre, affranchi d'Auguste;Publilius Syrus;La...",https://catalogue.bnf.fr/ark:/12148/cb310997412,,,Non trouvé

In [64]:
def verification_auteur(row):
    auteur_True,paraauteur_True,auteur_predict,paraauteur_predict=row["Identifiant auteur"],row["Identifiant para-auteur"],row["Auteur_prédit"],row["Autre_auteur_prédit"]
    auteur_True=auteur_True.split(";") if auteur_True else []
    auteur_True=set([code for code in auteur_True if "https://catalogue.bnf.fr/" in code])
    paraauteur_True=paraauteur_True.split(";") if paraauteur_True else []
    paraauteur_True=set([code for code in paraauteur_True if "https://catalogue.bnf.fr/" in code])
    auteur_predict=auteur_predict.split(";") if auteur_predict else []
    auteur_predict=set([name[name.find("http"):-2] for name in auteur_predict])
    paraauteur_predict=paraauteur_predict.split(";") if paraauteur_predict else []
    paraauteur_predict=set([name[name.find("http"):-2] for name in paraauteur_predict])
    results=dict()
    if auteur_True==auteur_predict:
        if auteur_True:
            results["Auteur"]="ok!"
        else:
            results["Auteur"]="ok(vide)"
    else:
        result={"Auteur présent":0,"Auteur placé en para-auteur":0,"Auteur absent":0,"Auteur ajouté":0}
        for auteur in auteur_True:
            if auteur in auteur_predict:
                result["Auteur présent"]+=1
            elif auteur in paraauteur_predict:
                result["Auteur placé en para-auteur"]+=1
            else:
                result["Auteur absent"]+=1
        for auteur in auteur_predict:
            if auteur not in auteur_True and auteur not in paraauteur_True:
                result["Auteur ajouté"]+=1
        listtemp=[]
        for k,v in result.items():
            if v>0:
                listtemp.append(k)
        if not listtemp:
            listtemp=["ok(vide)"]
        elif listtemp==["Auteur présent"]:
            listtemp=["ok!"]
        results['Auteur']=" ; ".join(listtemp)

    if paraauteur_True==paraauteur_predict:
        if paraauteur_True:
            results["Para-auteur"]="ok!"
        else:
            results["Para-auteur"]="ok(vide)"
    else:
        result={"Para-auteur présent":0,"Para-auteur placé en auteur":0,"Para-auteur absent":0,"Para-auteur ajouté":0}
        for paraauteur in paraauteur_True:
            if paraauteur in paraauteur_predict:
                result["Para-auteur présent"]+=1
            elif paraauteur in auteur_predict:
                result["Para-auteur placé en auteur"]+=1
            else:
                result["Para-auteur absent"]+=1
        for paraauteur in paraauteur_predict:
            if paraauteur not in paraauteur_True:
                result["Para-auteur ajouté"]+=1
        listtemp=[]
        for k,v in result.items():
            if v>0:
                listtemp.append(k)
        if not listtemp:
            listtemp=["ok(vide)"]
        elif listtemp==["Para-auteur présent"]:
            listtemp=["ok!"]
        results['Para-auteur']=" ; ".join(listtemp)
    return pd.Series(results)
df[['predict_auteur_verif','predict_paraauteur_verif']]=df.apply(verification_auteur,axis=1,result_type="expand")

#Modification des résultats pours quelques auteurs correctement identifiés mais dont les données d'entraînement donne un mauvais code (un code plus valable ?)
df.loc[(df["Auteur"] == "J. J. Rousseau") & (df["Auteur_prédit"] == "Rousseau, Jean-Jacques (1712-1778) [https://catalogue.bnf.fr/ark:/12148/cb119228797]"), "auteur_verification"] = "ok"
df.loc[(df["Auteur"] == "Gresset") & (df["Auteur_prédit"] == "Gresset, Jean-Baptiste-Louis (1709-1777) [https://catalogue.bnf.fr/ark:/12148/cb12063085m]"), "auteur_verification"] = "ok"
df.loc[(df["Auteur"] == "J. Racine") & (df["Auteur_prédit"] == "Racine, Jean (1639-1699) [https://catalogue.bnf.fr/ark:/12148/cb120076761]"), "auteur_verification"] = "ok"
df.loc[(df["Auteur"] == "Ovide") & (df["Auteur_prédit"] == "Ovide (0043 av. J.-C.-0017) [https://catalogue.bnf.fr/ark:/12148/cb119183166]"), "auteur_verification"] = "ok"

print(f"--- Sur tous les textes : {len(df)} textes")
print(df['predict_auteur_verif'].value_counts())
print(" ")
print(df['predict_paraauteur_verif'].value_counts())
print(" ")
verif_ouvrage="Prediction correcte"
print(f"--- Sur les textes correctement identifiés : {len(df[df['predict_ouvrage_verif']==verif_ouvrage])} textes")
print(df[df['predict_ouvrage_verif']==verif_ouvrage]['predict_auteur_verif'].value_counts())
print(" ")
print(df[df['predict_ouvrage_verif']==verif_ouvrage]['predict_paraauteur_verif'].value_counts())
print(" ")
verif_ouvrage="Hors BNF"
print(f"--- Sur les textes hors BNF (potentiellement identifiés quand même) : {len(df[df['predict_ouvrage_verif']==verif_ouvrage])} textes")
print(df[df['predict_ouvrage_verif']==verif_ouvrage]['predict_auteur_verif'].value_counts())
print(" ")
print(df[df['predict_ouvrage_verif']==verif_ouvrage]['predict_paraauteur_verif'].value_counts())
print(" ")
verif_ouvrage="Pas le même ouvrage"
print(f"--- Sur les textes liés à un autre de la BNF que celui prévu : {len(df[df['predict_ouvrage_verif']==verif_ouvrage])} textes")
print(df[df['predict_ouvrage_verif']==verif_ouvrage]['predict_auteur_verif'].value_counts())
print(" ")
print(df[df['predict_ouvrage_verif']==verif_ouvrage]['predict_paraauteur_verif'].value_counts())

--- Sur tous les textes
predict_auteur_verif
ok!                                               1091
Auteur absent                                      358
ok(vide)                                           306
Auteur ajouté                                      145
Auteur absent ; Auteur ajouté                      101
Auteur présent ; Auteur ajouté                      52
Auteur placé en para-auteur                         26
Auteur présent ; Auteur absent                      13
Auteur présent ; Auteur absent ; Auteur ajouté       7
Auteur placé en para-auteur ; Auteur ajouté          3
Auteur placé en para-auteur ; Auteur absent          3
Auteur présent ; Auteur placé en para-auteur         2
Name: count, dtype: int64

predict_paraauteur_verif
ok(vide)                                                                                       1653
Para-auteur ajouté                                                                              207
Para-auteur absent                                                                              103
ok!                                                                                              75
Para-auteur absent ; Para-auteur ajouté                                                          22
Para-auteur placé en auteur                                                                      15
Para-auteur présent ; Para-auteur ajouté                                                         13
Para-auteur présent ; Para-auteur absent ; Para-auteur ajouté                                     7
Para-auteur placé en auteur ; Para-auteur absent                                                  5
Para-auteur présent ; Para-auteur absent                                                          4
Para-auteur placé en auteur ; Para-auteur ajouté                                                  2
Para-auteur présent ; Para-auteur placé en auteur ; Para-auteur absent ; Para-auteur ajouté       1
Name: count, dtype: int64

--- Sur les textes correctement identifiés
predict_auteur_verif
ok!                                               949
ok(vide)                                          129
Auteur ajouté                                      75
Auteur absent ; Auteur ajouté                      53
Auteur présent ; Auteur ajouté                     48
Auteur placé en para-auteur                        21
Auteur absent                                      15
Auteur présent ; Auteur absent                     10
Auteur placé en para-auteur ; Auteur ajouté         2
Auteur présent ; Auteur absent ; Auteur ajouté      2
Name: count, dtype: int64

predict_paraauteur_verif
ok(vide)                                                                                       992
Para-auteur ajouté                                                                             137
ok!                                                                                             64
Para-auteur absent                                                                              56
Para-auteur absent ; Para-auteur ajouté                                                         16
Para-auteur placé en auteur                                                                     15
Para-auteur présent ; Para-auteur ajouté                                                        10
Para-auteur présent ; Para-auteur absent ; Para-auteur ajouté                                    7
Para-auteur présent ; Para-auteur absent                                                         3
Para-auteur placé en auteur ; Para-auteur absent                                                 3
Para-auteur présent ; Para-auteur placé en auteur ; Para-auteur absent ; Para-auteur ajouté      1
Name: count, dtype: int64

--- Sur les textes hors BNF (potentiellement identifiés quand même)
predict_auteur_verif
ok(vide)                                          59
Auteur ajouté                                     55
ok!                                               49
Auteur absent                                     46
Auteur absent ; Auteur ajouté                     14
Auteur placé en para-auteur ; Auteur absent        3
Auteur présent ; Auteur ajouté                     2
Auteur présent ; Auteur absent                     2
Auteur présent ; Auteur placé en para-auteur       1
Auteur présent ; Auteur absent ; Auteur ajouté     1
Name: count, dtype: int64

predict_paraauteur_verif
ok(vide)                                   180
Para-auteur ajouté                          33
Para-auteur absent                          15
ok!                                          3
Para-auteur absent ; Para-auteur ajouté      1
Name: count, dtype: int64

--- Sur les textes liés à un autre de la BNF que celui prévu
predict_auteur_verif
ok!                                               93
Auteur absent ; Auteur ajouté                     34
ok(vide)                                          19
Auteur ajouté                                     15
Auteur absent                                     12
Auteur placé en para-auteur                        5
Auteur présent ; Auteur absent ; Auteur ajouté     4
Auteur présent ; Auteur ajouté                     2
Auteur placé en para-auteur ; Auteur ajouté        1
Auteur présent ; Auteur absent                     1
Auteur présent ; Auteur placé en para-auteur       1
Name: count, dtype: int64

predict_paraauteur_verif
ok(vide)                                            123
Para-auteur ajouté                                   37
ok!                                                   8
Para-auteur absent                                    6
Para-auteur absent ; Para-auteur ajouté               5
Para-auteur présent ; Para-auteur ajouté              3
Para-auteur placé en auteur ; Para-auteur absent      2
Para-auteur placé en auteur ; Para-auteur ajouté      2
Para-auteur présent ; Para-auteur absent              1
Name: count, dtype: int64

In [66]:
#Visualisation direct des résultats d'un type (auteur)
verif_ouvrage="Hors BNF" #En choisir un parmi "Prediction correcte", "Non trouvé", "Hors BNF", "Pas le même ouvrage"
verif_auteur="ok!"  #En choisir un parmi "ok!","ok(vide)","Auteur ajouté","Auteur absent","Auteur présent","Auteur placé en para-auteur"
df[(df['predict_ouvrage_verif']==verif_ouvrage) & (df['predict_auteur_verif'].str.contains(verif_auteur))][["Titre","Auteur","Identifiant auteur","Identifiant para-auteur","Auteur_prédit","Autre_auteur_prédit",'predict_auteur_verif','predict_paraauteur_verif']]

,Titre,Auteur,Identifiant auteur,Identifiant para-auteur,Auteur_prédit,Autre_auteur_prédit,predict_auteur_verif,predict_paraauteur_verif
0,"Classiques français. Poésies de Malherbe, plus...",Malherbe,https://catalogue.bnf.fr/ark:/12148/cb12327103c,,"Malherbe, François de (1555-1628) [ https://ca...",,ok!,ok(vide)
13,Nouvelles Méditations poétiques. Troisième édi...,Alphonse de Lamartine,https://catalogue.bnf.fr/ark:/12148/cb119108008,,"Lamartine, Alphonse de (1790-1869) [ https://c...",Thibaron (18..-1885) [ https://catalogue.bnf.f...,ok!,Para-auteur ajouté
37,"Ecole des vieillards, comédie en cinq actes et...",Casimir Delavigne,https://catalogue.bnf.fr/ark:/12148/cb12052639n,,"Delavigne, Casimir (1793-1843) [ https://catal...",,ok!,ok(vide)
53,Elémens de la grammaire latine,Lhomond,https://catalogue.bnf.fr/ark:/12148/cb12170155m,,"Lhomond, Charles-François (1727-1794) [ https:...",,ok!,ok(vide)
81,Répertoire du Théâtre-Français. Œuvres complèt...,Crébillon,https://catalogue.bnf.fr/ark:/12148/cb11998713x,,"Crébillon, Prosper de (1674-1762) [ https://ca...",,ok!,ok(vide)
91,"Cadet Buteux à l’Ecole des vieillards, pot-pou...","M. Jacinthe Leclere, convive des Soupers de Momus",https://catalogue.bnf.fr/ark:/12148/cb17748957j,,"Leclère, Jacinthe [ https://catalogue.bnf.fr/a...",,ok!,ok(vide)
104,The Works of lord Byron,lord Byron,https://catalogue.bnf.fr/ark:/12148/cb11894686q,,"Byron, George Gordon (1788-1824) [ https://cat...","Lake, J. W. (17..?-18..) [ https://catalogue.b...",ok!,Para-auteur ajouté
244,"Elémens de la grammaire française, par C. F. L...","C. F. Lhomond, professeur émérite en la ci-dev...",https://catalogue.bnf.fr/ark:/12148/cb12170155m,,"Lhomond, Charles-François (1727-1794) [ https:...",,ok!,ok(vide)
245,"Grammaire française de Lhomond, à l'usage des ...",Lhomond,https://catalogue.bnf.fr/ark:/12148/cb12170155m,https://catalogue.bnf.fr/ark:/12148/cb13005487s,"Lhomond, Charles-François (1727-1794) [ https:...",,ok!,Para-auteur absent
258,"Phædri, liberti Augusti fabulæ. Nova editio st...","Phèdre, affranchi d'Auguste",https://catalogue.bnf.fr/ark:/12148/cb11985800x,,Phèdre (0015? av. J.-C.-0054) [ https://catalo...,,ok!,ok(vide)
262,Abridgment of Murray's English grammar. With a...,Lindley Murray,https://catalogue.bnf.fr/ark:/12148/cb13327218t,,"Murray, Lindley (1745-1826) [ https://catalogu...",,ok!,ok(vide)
291,"Traité de la conjugaison des verbes, ouvrage q...",E. A. Lequien,https://catalogue.bnf.fr/ark:/12148/cb179487173,,"Lequien, Edme-Alexandre (1779-1835) [ https://...",,ok!,ok(vide)
317,Œuvres complètes de Voltaire. Tomes XXXVIII et...,Voltaire,https://catalogue.bnf.fr/ark:/12148/cb11928669t,,Voltaire (1694-1778) [ https://catalogue.bnf.f...,,ok!,ok(vide)
350,Jane Shore,Mme Marie d’Heures,https://catalogue.bnf.fr/ark:/12148/cb13322071h,,"Heures, Marie d' (1786-1845) [ https://catalog...",,ok!,ok(vide)
427,Œuvres complètes de Regnard. Tome III,Regnard,https://catalogue.bnf.fr/ark:/12148/cb11921388k,,"Regnard, Jean-François (1655-1709) [ https://c...","Crapelet, Georges-Adrien (1789-1842) [ https:/...",ok!,Para-auteur ajouté
432,"Luxe et Indigence, ou le Ménage parisien, comé...",M. d’Epagny,https://catalogue.bnf.fr/ark:/12148/cb130128861,,"Épagny, d' (1787-1868) [ https://catalogue.bnf...",,ok!,ok(vide)
453,Essais poétiques,Mlle Delphine Gay,https://catalogue.bnf.fr/ark:/12148/cb11905056p,,"Girardin, Delphine de (1804-1855) [ https://ca...",,ok!,ok(vide)
476,"Le Pilote, roman américain. Par M. Cooper ; tr...",M. Cooper,https://catalogue.bnf.fr/ark:/12148/cb118975923,,"Cooper, James Fenimore (1789-1851) [ https://c...",,ok!,ok(vide)
530,Collection de lettres et articles publiés jusq...,"Paul-Louis Courier, vigneron",https://catalogue.bnf.fr/ark:/12148/cb12338809t,,"Courier, Paul-Louis (1772-1825) [ https://cata...",,ok!,ok(vide)
637,Exercices d'analyse logique. Par Ch. Constant ...,Ch. Constant Letellier,https://catalogue.bnf.fr/ark:/12148/cb13005487s,,"Le Tellier, Constant (1768-1846) [ https://cat...",,ok!,ok(vide)
638,Exercices sur l’application des règles des par...,Ch. C. Letellier,https://catalogue.bnf.fr/ark:/12148/cb13005487s,,"Le Tellier, Constant (1768-1846) [ https://cat...",,ok!,ok(vide)
769,Elémens de la grammaire française. XVIIIe édition,Lhomond,https://catalogue.bnf.fr/ark:/12148/cb12170155m,,"Lhomond, Charles-François (1727-1794) [ https:...",,ok!,ok(vide)
772,Elémens de la grammaire française. Par Lhomond...,Lhomond,https://catalogue.bnf.fr/ark:/12148/cb12170155m,,"Lhomond, Charles-François (1727-1794) [ https:...",,ok!,ok(vide)
783,"Elisabeth, ou les exilés de Sibérie. Par Mme C...",Mme Cottin,https://catalogue.bnf.fr/ark:/12148/cb12442990q,,"Cottin, Sophie (1770-1807) [ https://catalogue...",,ok!,ok(vide)
792,Le Diable boiteux,Lesage,https://catalogue.bnf.fr/ark:/12148/cb11912638w,,"Lesage, Alain-René (1668-1747) [ https://catal...",,ok!,ok(vide)
841,"Elémens de la grammaire latine, à l'usage des ...",Lhomond,https://catalogue.bnf.fr/ark:/12148/cb12170155m,,"Lhomond, Charles-François (1727-1794) [ https:...",,ok!,ok(vide)
850,"Fortune et revers, ou l'aventurier portugais",L. T. Gilbert,https://catalogue.bnf.fr/ark:/12148/cb135279977,,"Gilbert, L. T. (1780-1827) [ https://catalogue...",,ok!,ok(vide)
853,Histoire de Guzman d’Alfarache,Lesage,https://catalogue.bnf.fr/ark:/12148/cb11912638w,,"Lesage, Alain-René (1668-1747) [ https://catal...",,ok!,ok(vide)
890,Principes de littérature. Par l'abbé Batteux. ...,abbé Batteux,https://catalogue.bnf.fr/ark:/12148/cb118905556,https://catalogue.bnf.fr/ark:/12148/cb10839801w,"Batteux, Charles (1713-1780) [ https://catalog...","Allais, E. P. [ https://catalogue.bnf.fr/ark:/...",ok!,ok!
906,"La Grammaire ramenée à ses principes naturels,...","J. E. Serreau, receveur principal des contribu...",https://catalogue.bnf.fr/ark:/12148/cb10485690...,,"Boussi, François Narcisse (1795-1868) [ https:...",,ok!,ok(vide)
1049,"Arte de hablar bien frances, o gramatica compl...",don Pedro Nicolas Chantreau,https://catalogue.bnf.fr/ark:/12148/cb12159261k,https://catalogue.bnf.fr/ark:/12148/cb106065888,"Chantreau, Pierre-Nicolas (1741-1808) [ https:...","Nuñez de Taboada, Manuel [ https://catalogue.b...",ok!,ok!
1132,Nouvelle Grammaire française sur un plan très-...,M. Noel:M. Chapsal,https://catalogue.bnf.fr/ark:/12148/cb12171008...,,"Noël, François (1756-1841) [ https://catalogue...",,ok!,ok(vide)
1139,Le Bachelier de Salamanque,Lesage,https://catalogue.bnf.fr/ark:/12148/cb11912638w,,"Lesage, Alain-René (1668-1747) [ https://catal...",,ok!,ok(vide)
1240,"Grammaire universelle, classique et polémique",Ch. Ant. Lefrançois de Hautevesne,https://catalogue.bnf.fr/ark:/12148/cb106928342,,"Le François de Hautevesne, Ch.-Ant. [ https://...",,ok!,ok(vide)
1250,Cours de thèmes grecs,"Louis Vaucher, docteur ès-lettres",https://catalogue.bnf.fr/ark:/12148/cb10337087w,https://catalogue.bnf.fr/ark:/12148/cb31548319c,"Vaucher, Louis (1799-1867) [ https://catalogue...",,ok!,Para-auteur absent
1311,"La mort de Louis XVIII, roi de France et de Na...","Eugène de Pradel, de plusieurs académies et so...",https://catalogue.bnf.fr/ark:/12148/cb14490266r,,"Pradel, Eugène de (1784-1857) [ https://catalo...",,ok!,ok(vide)
1347,"Le Meurtre, traduit de l'anglais de Henriette ...",Henriette Lée,https://catalogue.bnf.fr/ark:/12148/cb10245159g,,"Lee, Harriet (1757-1851) [ https://catalogue.b...",,ok!,ok(vide)
1362,"Trois Messéniennes, par M. Odry ,auteur du poë...","M. Odry, auteur du poëme des Gendarmes et du c...",https://catalogue.bnf.fr/ark:/12148/cb14656349d,[PFSGKZ],"Odry, Jacques Charles (1781-1853) [ https://ca...",,ok!,ok(vide)
1428,"L’Espion, roman américain, par M. Cooper ; tra...","M. Cooper, américain",https://catalogue.bnf.fr/ark:/12148/cb118975923,,"Cooper, James Fenimore (1789-1851) [ https://c...","Defauconpret, Auguste-Jean-Baptiste (1767-1843...",ok!,Para-auteur ajouté
1470,"Œuvres de Rabelais, édition variorum, augmenté...",Rabelais,https://catalogue.bnf.fr/ark:/12148/cb11920939s,[Leduchat];https://catalogue.bnf.fr/ark:/12148...,"Rabelais, François (1494?-1553) [ https://cata...","Le Duchat, Jacob [ https://catalogue.bnf.fr/ar...",ok!,Para-auteur absent ; Para-auteur ajouté
1747,"La Religion, poëme de Louis Racine, mis à la p...",Louis Racine,https://catalogue.bnf.fr/ark:/12148/cb12002053h,https://catalogue.bnf.fr/ark:/12148/cb12519652k,"Racine, Louis (1692-1763) [ https://catalogue....","Fontanier, Pierre (1768-1844) [ https://catalo...",ok!,ok!
1831,"Fables de Florian ; nouvelle édition, revue et...",Florian,https://catalogue.bnf.fr/ark:/12148/cb11902963q,,"Florian, Jean-Pierre Claris de (1755-1794) [ h...",,ok!,ok(vide)
1858,"Ma Femme se marie, vaudeville en un acte ; par...",M. Duvert;M. Vianadt,https://catalogue.bnf.fr/ark:/12148/cb10546561...,,Vianadt (1797-1825) [ https://catalogue.bnf.fr...,,ok!,ok(vide)
1861,"L’Etrangère. Par le vicomte d'Arlincourt, avec...",vicomte d’Arlincourt,https://catalogue.bnf.fr/ark:/12148/cb12253595f,https://catalogue.bnf.fr/ark:/12148/cb14961556r,"Arlincourt, Charles-Victor d' (1788-1856) [ ht...",,ok!,Para-auteur absent
1889,Bibliothèque française. Œuvres de Mathurin Reg...,Regnier,https://catalogue.bnf.fr/ark:/12148/cb12018202t,,"Régnier, Mathurin (1573-1613) [ https://catalo...",,ok!,ok(vide)
1904,Répertoire du Théâtre-Français. Œuvres complèt...,Regnard,https://catalogue.bnf.fr/ark:/12148/cb11921388k,,"Regnard, Jean-François (1655-1709) [ https://c...","Crapelet, Georges-Adrien (1789-1842) [ https:/...",ok!,Para-auteur ajouté
2029,"Œuvres inédites de Florian, recueillies par R....",Florian,https://catalogue.bnf.fr/ark:/12148/cb11902963q,https://catalogue.bnf.fr/ark:/12148/cb119063124,"Florian, Jean-Pierre Claris de (1755-1794) [ h...",,ok!,Para-auteur absent
2058,"Un Jour d’embarras, comédie-vaudeville en un a...",M. Saint-Alme;M. Etienne Arago,https://catalogue.bnf.fr/ark:/12148/cb11579900...,,"Lepoitevin de L'Égreville, Auguste (1791-1854)...",,ok!,ok(vide)
2059,"Le Grenier du poëte, vaudeville en un acte, re...",M. Benjamin;M. Ponet,https://catalogue.bnf.fr/ark:/12148/cb12279578...,,"Ponet, Louis Portelette dit Louis [ https://ca...",,ok!,ok(vide)

In [ ]:
#Si vous êtes plus à l'aise sur logiciel : vous pouvez le re-sauvegarder avec les colonnes de verification ainsi
adresse="" #adresse de sauvegarde
df.to_csv(adresse, encoding="utf-8", sep=";", header=True, index=False)